env:
  global:
  - DOCKER_HUB_USERNAME=arcaoss
  - secure: "exAH0tbfFX/MZLx5TO/rEPoVDLHyv1+twdtLu+imIDguH6GcVeyOe9jTZf766dEF+lql0J/jXVodMG7wYg5cvUQx8SRSCaS380xSD5lXbMmnvoou37U1/cPPuL41SOBQayEm1iKZ5uMmBpGY1vIT0xaI6dzUeLaxzAmt4bi9RB6pRSmXfM9qtopJLjp/4Vp81tqbXTXOqnc/l+ZiJjabl205PDxJG+3vzCWI2/2S6B+Q8n6ka+RyHZCrpkWZbzAgyfkO5swkum06q+c7a/EyTcV9k1z3HQGAe2gYSkFb3KMBV7x+vP7IFX4R8b15VtdxmJZcFyPvKponMyo1KoNNxsR/nQmDNTro6n9SZ72F3Bs3I4x3asQwi7a8qj7sty4fymFbifoU6pP1xUO9nj0uxSSmHd7/Wmxpf0NAlLjkPhW5TTzqMUrExDvJXe13zd+jxO89cYYd1/Kbj5aiwH8UHqQM7ATicqEkAl5QSGzNKI4sWjv8CdhwE4YVy8VWTpF2ijHUPWqAHTuzkuOoU01+BQAD0koIzWiw1OCRO1AFD570J+oApOQxxql5WsvQRhltpbgYEfocButmOiNl896BqZv4DALNa4saidRfFco/2xWJhpMKNu1aD19et6llNzRgMDLIZgkJMIymLwGt20zLoxRAppMaVJBhk9IjsF4Kd68="
language: python
dist: xenial
python:
- '3.6'
- '3.7'

cache:
- pip
notifications:
  email: false
sudo: required
services:
- docker
install:
- pip install codecov mypy
- pip install -r requirements.txt  # so travis pip cache can actually cache something
- python setup.py install
before_script:
- docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD"
script:
- python setup.py test 2>error.log
- mypy arca || echo "Optional MyPy check failed"
after_script:
- cat error.log
- sleep 1
after_success:
- codecov
branches:
  only:
  - master
  - /release-v[0-9]+/
deploy:
  provider: script
  skip_cleanup: true
  script: python setup.py deploy_docker_bases
  on:
    branch: master
    repo: mikicz/arca
    python: '3.7'
