env:
  global:
  - DOCKER_HUB_USERNAME=arcaoss
  - secure: j0+kOTtkmv7vaB+nQVhYWaCpNsqPi3cfIz6rHVux3pEgAaJDn7ML6Dhdo8hzP3+duVoPHfttOsJSrRrnUK85s3WuU0y2RAds3X89+Rnp0lsf6rn/Pt6eQ01lXDee2ZUGJp4tdDQJUn30rXHEKy8dWYJTma9nQLJ9V0K4DuYMkmTWKrmxGD+95bFkSdRP7fBJ3fc1HCEqNQP/otOPrG/P5i2eKTRsvE2iIg3vMPcMoTSZgMUu4ZTco9AGH+e1r7rfeF9ttjA8kDzWqbhDAO+L4+BrFyVNKPwq/LPyqFvi/Q7hp3NRehlX7J0ySQ/+sxRWG5K7o2ACGu9+7M1+8rACFG7G+Hw3dvQPc1SwSYi8fBCwouXUfEXJPvXPmvHmF6s2mBZ6ik/FIpJTBTrYQcdWQFgam+zw/j0UnKq2BUCujfPqZx7P3flqLSaG734P20jV+E4Mnl2Qwp10uPqEBg0I6fVVFWC5CgyYzMtLgJRDltnOH+Bec1+UdWJCnunmr3JSdaqb1Y58O6t7L5pXulCjGUq+vnU5rAizIHp5P9ky9EUnWRB1gP9VuKzRJZcuPLIwJLZIYMbrO2DyutKY0oWk5Uun8p6F7jYBzaWxlZJKUt2xmCW/P+i0+iTDEjzPi+R/JopUEw0djPSK96kb7PRXEo0+Cmzusl6TCVHxNuUiFK0=
language: python
dist: xenial
python:
- '3.6'
- '3.7'
- '3.8'

cache:
- pip
notifications:
  email: false
sudo: required
services:
- docker
install:
- pip install codecov mypy
- pip install -r requirements.txt  # so travis pip cache can actually cache something
- python setup.py install
before_script:
- docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD"
script:
- python setup.py test 2>error.log
- mypy arca || echo "Optional MyPy check failed"
after_script:
- cat error.log
- sleep 1
after_success:
- codecov
branches:
  only:
  - master
  - /release-v[0-9]+/
deploy:
  provider: script
  skip_cleanup: true
  script: python setup.py deploy_docker_bases
  on:
    branch: master
    repo: pyvec/arca
    python: '3.7'
